{{- range $portMapIndex, $portMapUnused := $.Values.service.ports }}
{{- if eq $portMapIndex 0 }}
apiVersion: v1
kind: Service
metadata:
  {{- if $.Values.service.name }}
  name: {{ $.Values.service.name | quote }}
  {{- else }}
  name: {{ $.Release.Name | quote }}
  {{- end }}
  labels:
    "app.kubernetes.io/name": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    {{- range $labelName, $labelValue := $.Values.service.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- range $annotationName, $annotationValue := $.Values.service.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
spec:
  externalIPs:
    {{- range $externalIPIndex, $externalIP := $.Values.service.externalIPs }}
    - {{ $externalIP }}
    {{- end }}
  ports:
    {{- range $portMapIndex, $portMap := $.Values.service.ports }}
    - name: "port-{{ $portMapIndex }}"
      port: {{ $portMap.port }}
      {{- if $portMap.containerPort }}
      targetPort: {{ $portMap.containerPort }}
      {{- else }}
      targetPort: {{ $portMap.port }}
      {{- end }}
      protocol: {{ $portMap.protocol | default "TCP" | quote }}
    {{- end }}
  selector:
    "app.kubernetes.io/name": "devspace-app"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
  type: {{ $.Values.service.type | default "ClusterIP" | quote }}
---

{{- range $rulesIndex, $rulesUnused := $.Values.ingress.rules }}
{{- if eq $rulesIndex 0 }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- if $.Values.ingress.name }}
  name: {{ $.Values.ingress.name | quote }}
  {{- else }}
  {{- if $.Values.service.name }}
  name: "{{ $.Values.service.name }}"
  {{- else }}
  name: "{{ $.Release.Name }}"
  {{- end }}
  {{- end }}
  labels:
    "app.kubernetes.io/name": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    {{- range $labelName, $labelValue := $.Values.ingress.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- range $annotationName, $annotationValue := $.Values.ingress.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
spec:
  rules:
  {{- range $ingressRuleIndex, $ingressRule := $.Values.ingress.rules }}
  - host: {{ $ingressRule.host | quote }}
    http:
      paths:
      - backend:
          {{- if $.Values.service.name }}
          serviceName: {{ $.Values.service.name | quote }}
          {{- else }}
          serviceName: {{ $.Release.Name | quote }}
          {{- end }}
          servicePort: {{ $portMap.port }}
        {{- if $ingressRule.path }}
        path: {{ $ingressRule.path | quote }}
        {{- else }}
        path: /
        {{- end }}
  {{- end }}
  tls:
  {{- range $ingressRuleIndex, $ingressRule := $.Values.ingress.rules }}
  - hosts:
    - {{ $ingressRule.host }}
    {{- if and (not $ingressRule.tls) $.Values.ingress.tls }}
    {{- if eq $.Values.ingress.tls "true" }}
    {{- if $.Values.ingress.name }}
    secretName: {{ $.Values.ingress.name | quote }}
    {{- else }}
    {{- if $.Values.service.name }}
    secretName: {{ $.Values.service.name | quote }}
    {{- else }}
    secretName: {{ $.Release.Name | quote }}
    {{- end }}
    {{- end }}
    {{- else }}
    secretName: {{ $.Values.ingress.tls | quote }}
    {{- end }}
    {{- else }}
    {{- if eq $ingressRule.tls "true" }}
    {{- if $.Values.ingress.name }}
    secretName: {{ $.Values.ingress.name | quote }}
    {{- else }}
    {{- if $.Values.service.name }}
    secretName: {{ $.Values.service.name | quote }}
    {{- else }}
    secretName: {{ $.Release.Name | quote }}
    {{- end }}
    {{- end }}
    {{- else }}
    secretName: {{ $ingressRule.tls | quote }}
    {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}

{{- end }}
{{- end }}