{{- range $portMapIndex, $portMapUnused := $.Values.service.ports }}
{{- if eq $portMapIndex 0 }}
apiVersion: v1
kind: Service
metadata:
  {{- if $.Values.service.name }}
  name: {{ $.Values.service.name | quote }}
  {{- else }}
  name: {{ $.Release.Name | quote }}
  {{- end }}
  labels:
    "app.kubernetes.io/name": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
spec:
  externalIPs:
    {{- range $externalIPIndex, $externalIP := $.Values.service.externalIPs }}
    - {{ $externalIP }}
    {{- end }}
  ports:
    {{- range $portMapIndex, $portMap := $.Values.service.ports }}
    - name: "port-{{ $portMapIndex }}"
      port: {{ $portMap.port }}
      {{- if $portMap.containerPort }}
      targetPort: {{ $portMap.containerPort }}
      {{- else }}
      targetPort: {{ $portMap.port }}
      {{- end }}
      protocol: {{ $portMap.protocol | default "TCP" | quote }}
    {{- end }}
  selector:
    "app.kubernetes.io/name": "devspace-app"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
  type: {{ $.Values.service.type | default "ClusterIP" | quote }}
---

{{- range $portMapIndex, $portMap := $.Values.service.ports }}
{{- if $portMap.ingress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- if $portMap.ingress.name }}
  name: {{ $portMap.ingress.name | quote }}
  {{- else }}
  {{- if $.Values.service.name }}
  name: "{{ $.Values.service.name }}-{{ $portMap.port }}"
  {{- else }}
  name: "{{ $.Release.Name }}-{{ $portMap.port }}"
  {{- end }}
  {{- end }}
spec:
  rules:
  - host: {{ $portMap.ingress.host | quote }}
    http:
      paths:
      - backend:
          {{- if $.Values.service.name }}
          serviceName: {{ $.Values.service.name | quote }}
          {{- else }}
          serviceName: {{ $.Release.Name | quote }}
          {{- end }}
          servicePort: {{ $portMap.port }}
        {{- if $portMap.ingress.path }}
        path: {{ $portMap.ingress.path | quote }}
        {{- else }}
        path: /
        {{- end }}
---
{{- end }}
{{- end }}

{{- end }}
{{- end }}