#### DevSpace Helm Chart ####
# This is a highly configurable Helm chart. For information on how to configure this file,
# take a look at the documentation: http://devspace.cloud/docs/chart/basics/devspace-helm-chart

# A list of containers that should run the pods of this component
containers: []

service:
  type: ClusterIP
  labels: {}
  annotations: {}
  ports:
  - port: 3000
    ingress:
      hostname: XXXX
  - port: 3003
    ingress:
      hostname: XXXX
  externalIPs: []

labels: {}
annotations: {}

ingress:
  labels: {}
  annotations: {}
  tls: true
  rules:
  - hostname: 
    port: 
    tls: true

# Define persistent volumes here
# Then mount them in containers above
volumes: []

# Defines image pull secrets
# DevSpace CLI will append all pull secrets which are automatically created
# More infos on: https://devspace.cloud/docs/cli/images/pull-secrets
pullSecrets: []
